# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mplane/notification_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mplane/notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!mplane/notification_service.proto\x12\x04oran\"4\n\x13NotificationRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\">\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"%\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t2\xaf\x01\n\x13NotificationService\x12I\n\x10SendNotification\x12\x19.oran.NotificationRequest\x1a\x1a.oran.NotificationResponse\x12M\n\x16SubscribeNotifications\x12\x16.oran.SubscribeRequest\x1a\x19.oran.NotificationRequest0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mplane.notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONREQUEST']._serialized_start=43
  _globals['_NOTIFICATIONREQUEST']._serialized_end=95
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=97
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=159
  _globals['_SUBSCRIBEREQUEST']._serialized_start=161
  _globals['_SUBSCRIBEREQUEST']._serialized_end=198
  _globals['_NOTIFICATIONSERVICE']._serialized_start=201
  _globals['_NOTIFICATIONSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
